spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/jfix_db
    username: postgres
    password: truong123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  data:
    redis:
      port: 6379
      host: localhost


jwt:
  access-token-secret: qA8+q5EhbAnJd87/sCoWw9NGUYfjIYMX6JuNlYqfVOPdmDukMunYeiBbCnpf9mtIGFy7cJprtXQc5jSXfZoS8A==
  refresh-token-secret: Tg2W/71ZhTHiFuIcCk9EHnJ4wMLM/RpuqCWbJQv4kuyl0TjQLFOrRfU3aVskikVlSII4h3AyUaGriM7ww+s8Yg==
  access-token-expiration: 604800000  # 15p (900000ms)
  refresh-token-expiration: 604800000  # 7d (604800000ms)
