-- Bảng users
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text UNIQUE NOT NULL,
  role text DEFAULT 'USER' NOT NULL,
  name text DEFAULT 'User Default',
  email text UNIQUE NOT NULL,
  phone text UNIQUE NOT NULL,
  avatar text,
  is_deleted boolean DEFAULT false,
  password text NOT NULL,
  refresh_token text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng vocabularies
CREATE TABLE vocabularies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  word text NOT NULL,
  reading text,
  meaning text,
  example_with_reading text,
  example_without_reading text,
  example_meaning text,
  audio text,
  level text NOT NULL DEFAULT 'FREE',
  chapter text,
  section text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng grammars
CREATE TABLE grammars (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  romaji text,
  structure text NOT NULL,
  usage text,
  meaning text,
  example text,
  example_meaning text,
  level text NOT NULL DEFAULT 'FREE',
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng decks
CREATE TABLE decks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  description text,
  user_id integer,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng cards
CREATE TABLE cards (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deck_id integer,
  type text,
  item_id integer NOT NULL,
  skill text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng speaking_question
CREATE TABLE speaking_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  japanese_text text NOT NULL,
  vietnamese_text text NOT NULL,
  level text DEFAULT 'FREE',
  sample_answer_japanese text,
  sample_answer_vietnamese text,
  audio_url text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng free_talk_topic
CREATE TABLE free_talk_topics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  japanese_text text NOT NULL,
  vietnamese_text text NOT NULL,
  level text DEFAULT 'FREE',
  conversation_prompt text,
  sample_answer_vietnamese text,
  audio_url text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng study_logs
CREATE TABLE study_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  card_id integer NOT NULL,
  review_date timestamp NOT NULL DEFAULT (now()),
  repetition integer NOT NULL DEFAULT 0,
  intervals float NOT NULL DEFAULT 0,
  easiness_factor float NOT NULL DEFAULT 2.5,
  last_review_date timestamp,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng sentences
CREATE TABLE sentences (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  japanese_text text NOT NULL,
  vietnamese_text text NOT NULL,
  level text DEFAULT 'FREE',
  audio_url text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng paragraphs
CREATE TABLE paragraphs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  japanese_text text NOT NULL,
  vietnamese_text text NOT NULL,
  level text DEFAULT 'FREE',
  topic text,
  audio_url text,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng user_mistakes
CREATE TABLE user_mistakes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  card_id integer NOT NULL,
  user_input text NOT NULL,
  correct_answer text,
  identified_at timestamp DEFAULT (now()),
  feedback_provided text,
  was_corrected boolean DEFAULT false,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng user_error_analytics
CREATE TABLE user_error_analytics (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  card_id integer NOT NULL,
  frequency float,
  improvement_rate float,
  last_occurrence timestamp NOT NULL,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng correction_histories
CREATE TABLE correction_histories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_mistake_id integer NOT NULL,
  correction_attempt text,
  is_correct boolean NOT NULL DEFAULT false,
  error_correction_time timestamp DEFAULT (now()),
  attempt_number integer NOT NULL DEFAULT 1,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng user_achievements
CREATE TABLE user_achievements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  achievement_type text NOT NULL,
  achievement_date timestamp DEFAULT (now()),
  achievement_value integer NOT NULL,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng learning_goals
CREATE TABLE learning_goals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  target_level text,
  description text,
  daily_minutes integer,
  daily_vocab_target integer,
  target_date date,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng correction_histories
CREATE TABLE conversation_histories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  card_id integer NOT NULL,
  user_input text NOT NULL,
  ai_reply text,
  audio_reply text,
  user_mistake_id integer,
  create_date timestamp NOT NULL DEFAULT (now()),
  create_by text NOT NULL,
  update_date timestamp,
  update_by text,
  delete_date timestamp,
  delete_by text
);

-- Bảng user_daily_card_stats
CREATE TABLE user_daily_card_stats (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  stat_date DATE NOT NULL,
  card_count INTEGER NOT NULL
);

-- Bảng reports
CREATE TABLE reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL,
  card_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  item_type TEXT NOT NULL,
  content TEXT NOT NULL,
  create_date TIMESTAMP NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false
);

-- Bảng password_reset_tokens
CREATE TABLE password_reset_tokens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(6) NOT NULL,
  user_id INTEGER NOT NULL,
  expiry_date TIMESTAMP NOT NULL,
  is_used BOOLEAN DEFAULT FALSE NOT NULL,
  create_date TIMESTAMP NOT NULL
);

-- Thêm ràng buộc khóa ngoại
ALTER TABLE decks ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE cards ADD FOREIGN KEY (deck_id) REFERENCES decks (id);
ALTER TABLE study_logs ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE study_logs ADD FOREIGN KEY (card_id) REFERENCES cards (id);
ALTER TABLE user_mistakes ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_mistakes ADD FOREIGN KEY (error_type_id) REFERENCES error_types (id);
ALTER TABLE user_error_analytics ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_error_analytics ADD FOREIGN KEY (error_type_id) REFERENCES error_types (id);
ALTER TABLE correction_histories ADD FOREIGN KEY (user_mistake_id) REFERENCES user_mistakes (id);
ALTER TABLE user_achievements ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE learning_goals ADD FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE user_daily_card_stats ADD FOREIGN KEY (user_id) REFERENCES users (id);